language: go
dist: trusty

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev mercurial pkg-config wget -y
  - make test
  - wget "https://raw.githubusercontent.com/go-graphite/helper-scripts/master/travis-docker-build.sh" && chmod +x ./travis-docker-build.sh && ./travis-docker-build.sh carbonapi

git:
  depth: 200

matrix:
  include:
    - go: 1.x
      env:
        - BUILD_PACKAGES=true
    - go: 1.9.x
    - go: 1.10.x
    - go: master
